spring.main.banner-mode=OFF
spring.application.name=eventProgress

spring.datasource.url = jdbc:postgresql://localhost:5432/planner_db
spring.datasource.username= postgres
spring.datasource.password= alpr1453

spring.jpa.hibernate.ddl-auto= update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true

jwt.secret = 42356418907564267890809654789012
jwt.expiration = 86400000


server.port= 8081

